# docker-compose.yml
version: '3'

services:
  web:
    build: docker build -t shruti/hello-world:1.0 .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
